language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package publishOnlyWhenOnMaster
scala:
  - 2.11.6
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
notifications:
  email:
    - eugene.burmako@epfl.ch
    - denys.shabalin@typesafe.com
env:
  global:
   - SCALAMACROS_MAVEN_REALM="Sonatype Nexus Repository Manager"
   - SCALAMACROS_MAVEN_DOMAIN="oss.sonatype.org"
   - secure: "DJyMEptCZezSLUt/xjpaO4g2l/H6ISiAdA5FhbA2x1qYC6uvUdXko0n43GjpA7ONJFx1zrMgcfJF9Y7SCNtdQzgzkQ9hTzr5xIrieUzeJ0dq8yum+gFrgAkTySAfocPO8on8CS/OtTj9m3i/1t1oZouG7I/l9GXyYWfQFPl/UDs="
   - secure: "cFBNyn2VbVovOn6HhPCGdFSpLJbinGY5jPlIkwailaGjJ53VGwEfFeNuoy9fAt8cLYi2air6kkVQBNnr5E4lTyUtHr4pStpEBiOhq1j1OGQnnxRyQQYRrEwaXFRepYKAk0GMT9lj1/deZcUhOBqwuF96iRJ86OCdyqBsMKRisuk="
